language: "go"
sudo: required
services:
    - docker

# before_install:
#    - docker build -t ozgurkadarozgur/go-deployment .

# script:
#    - docker run ozgurkadarozgur/go-deployment

deploy: 
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "go-app"
    env: "GoApp-env-1"
    bucket_name: "go-app-bucket"
    bucket_path: "go-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
        secure: "$AWS_SECRET_ACCESS_KEY"